# Copyright (C) 2024 Cooper Lockrey

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# this is my docker compose yaml that includes qBittorrent, Lidarr, Readarr, Jackett, Watchtower
services:
  # Torrent client - qBittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${puid}
      - PGID=${pgid}
      - WEBUI_PORT=8080
    volumes:
      - ${media}/downloads:/downloads
      - ${config}/qbittorrent:/config
    ports:
      - 8080:8080
    restart: unless-stopped
  # Music scraper - Lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${puid}
      - PGID=${pgid}
    volumes:
      - ${media}/music:/music
      - ${media}/downloads:/downloads
      - ${config}/lidarr:/config
    ports:
      - 8686:8686
    restart: unless-stopped
  # Audio/E-book scraper - Readarr
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${puid}
      - PGID=${pgid}
    volumes:
      - ${media}/books:/books
      - ${media}/downloads:/downloads
      - ${config}/readarr:/config
    ports:
      - 8787:8787
    restart: unless-stopped
  # Tracker manager - Jackett
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${puid}
      - PGID=${pgid}
      - AUTO_UPDATE=true
    volumes:
      - ${config}/jackett:/config
      - ${media}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    ports:
      - 8191:8191
    restart: unless-stopped
  # Auto update - Watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   
    restart: unless-stopped